- name: play level variables
  hosts: local
  connection: local
  vars: # in shell we refer like name=surya , $surya while calling, if it is command $(PWD)
   name: surya
   course: ansible
   duration: 10 hours
   Trainer: siva kumar
  tasks:
  - name: apply play level variables
    ansible.builtin.debug:
     msg: "hello {{name}}, course: {{ course }}, duration: {{ duration }}, Trainer: {{ Trainer }}" # vars in ansible always surronded by ""

  tasks:
  - name: apply play level variables
    ansible.builtin.debug:
     msg: "hello {{name}}, course: {{ course }}, duration: {{ duration }}, Trainer: {{ Trainer }}" # vars in ansible always surronded by ""  