- name: calling variables from arguments
  hosts: local
  connection: local
  tasks:
  - name: calling from arguments
    ansible.builtin.debug:
     msg: "printing the argument passed variables {{ course }} and duration {{ duration }}"

